src/alfredo/web_experiments/routes.py
# pylint: disable=no-member
import collections
import csv
import hashlib
import io
import json
import os
import random
import re
import shutil
import zipfile
from datetime import datetime
from pathlib import Path
from uuid import uuid4

from alfred3 import data_manager
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from alfredo.export import make_str_bytes
from alfredo.forms import (
    ExperimentConfigForm,
    ExperimentScriptForm,
    FilterLogForm,
    NewScriptForm,
    WebExperimentForm,
)
from alfredo.models import Participant, User, WebExperiment
from alfredo.utils import (
    ScriptFile,
    ScriptString,
    create_fernet,
    display_directory,
    get_alfred_db,
    get_plugin_data_queries,
    get_user_collection,
)

web_experiments = Blueprint("web_experiments", __name__)


@web_experiments.route("/experiment/new", methods=["GET", "POST"])
@login_required
def new_experiment():

    form = WebExperimentForm()

    if form.validate_on_submit():

        exp = WebExperiment(
            title=form.title.data,
            author=current_user.username,
            author_id=current_user.id,
            version=form.version.data,
            description=form.description.data,
        )

        exp.available_versions.append(form.version.data)
        exp.directory_name = str(uuid4())
        exp.path = os.path.join(current_app.instance_path, "exp", exp.directory_name)

        # create experiment directory
        try:
            os.makedirs(exp.path)
        except OSError:
            flash(
                "Action aborted: The experiment directory already exists on the file system.",
                "danger",
            )
            return redirect(url_for("web_experiments.new_experiment"))

        # process script.py
        if form.script.data:
            script = ScriptFile(exp, form.script.data)
            script.load()
            script.parse()
            script.save()

        # set password protection if password is given
        if form.password.data:
            exp.public = False
            exp.password = form.password.data
        else:
            exp.public = True

        exp.save()  # IMPORTANT! Needed to create an exp ID

        # append an entry for the current experiment to the current user
        current_user.experiments.append(exp.id)  # pylint: disable=no-member
        current_user.save()

        flash("Your Experiment has been created.", "success")

        return redirect(
            url_for("web_experiments.user_experiments", username=current_user.username)
        )

    return render_template(
        "create_experiment.html",
        title="New Experiment",
        form=form,
        legend="New Experiment",
    )


@web_experiments.route("/<username>/<path:exp_title>", methods=["POST", "GET"])
@login_required
def experiment(username, exp_title):

    exp = WebExperiment.objects.get_or_404(  # pylint: disable=no-member
        title=exp_title, author=username
    )
    if exp.author != current_user.username:
        abort(403)

    # Set some status indicators

    if exp.active:
        status = "active"
        toggle_button = "Deactivate"
    else:
        status = "inactive"
        toggle_button = "Activate"

    if exp.public:
        password_protection = "disabled"
    else:
        password_protection = "enabled"

    # Query Database
    db = get_user_collection()

    f_id = {"exp_id": str(exp.id)}
    f_fin = {"exp_finished": True}
    f_ver = {"exp_version": exp.version}

    # Used versions
    alfred_versions = db.distinct("alfred_version", {**f_id, **f_fin})
    alfred_versions.sort()

    # Number of datasets
    n = {}
    n["total"] = db.count_documents(f_id)
    n["fin"] = db.count_documents({**f_id, **f_fin})
    n["unfin"] = n["total"] - n["fin"]
    n["current_ver"] = db.count_documents({**f_id, **f_ver})
    n["fin_current_ver"] = db.count_documents({**f_fin, **f_id, **f_ver})
    n["unfin_current_ver"] = n["current_ver"] - n["fin_current_ver"]
    n["individual_versions"] = {}

    # Number of datasets per version
    for v in exp.available_versions:
        f_ver = {"exp_version": v, **f_id}
        entry = {
            "total": db.count_documents(f_ver),
            "fin": db.count_documents({**f_fin, **f_ver}),
        }
        n["individual_versions"][v] = entry

    # start time
    group = {
        "_id": 1,
        "first": {"$min": "$exp_start_time"},
        "last": {"$max": "$exp_start_time"},
    }
    pipe = [{"$match": f_id}, {"$group": group}]
    times = list(db.aggregate(pipe))

    activity = {}
    if times:
        try:
            activity["first"] = datetime.fromtimestamp(times[0]["first"]).strftime(
                "%Y-%m-%d, %H:%M"
            )
            activity["last_time"] = datetime.fromtimestamp(times[0]["last"]).strftime(
                "%H:%M"
            )
            activity["last_date"] = datetime.fromtimestamp(times[0]["last"]).strftime(
                "%Y-%m-%d"
            )
        except TypeError:
            activity["first"] = times[0]["first"]
            activity["last_time"] = times[0]["last"]
            activity["last_date"] = "none"
    else:
        activity["first"] = "none"
        activity["last_time"] = "none"
        activity["last_date"] = "none"

    # Form for script.py upload
    form = NewScriptForm()

    if form.validate_on_submit() and form.script.data:

        # process script.py
        if form.script.data:
            script = ScriptFile(exp, form.script.data)
            script.load()
            script.parse()
            script.save()

        # update version
        if exp.version != form.version.data:
            exp.version = form.version.data
            exp.available_versions.append(exp.version)

        # save experiment
        exp.save()

        # redirect to experiment page
        flash("New script.py was uploaded successfully", "success")
        return redirect(
            url_for(
                "web_experiments.experiment", username=exp.author, exp_title=exp.title
            )
        )

    elif form.validate_on_submit():
        flash("No script.py was provided, so nothing happened.", "info")
        return redirect(
            url_for(
                "web_experiments.experiment", username=exp.author, exp_title=exp.title
            )
        )

    # pre-populate form
    form.version.data = exp.version

    return render_template(
        "experiment.html",
        experiment=exp,
        alfred_versions=alfred_versions,
        expid=str(exp.id),
        form=form,
        status=status,
        toggle_button=toggle_button,
        n=n,
        activity=activity,
        password_protection=password_protection,
    )


@web_experiments.route("/<username>/<path:exp_title>/script", methods=["GET", "POST"])
@login_required
def experiment_script(username, exp_title):

    exp = WebExperiment.objects.get_or_404(  # pylint: disable=no-member
        title=exp_title, author=username
    )

    if exp.author != current_user.username:
        abort(403)

    form = ExperimentScriptForm()

    if form.validate_on_submit():

        # update script
        script = ScriptString(exp, form.script.data)
        script.parse()
        script.save()

        # update version
        if exp.version != form.version.data:
            exp.version = form.version.data
            exp.available_versions.append(exp.version)

        # save simple updates
        exp.last_update = datetime.now

        # save experiment
        exp.save()

        # return to experiment page
        flash("Your experiment has been updated", "success")
        return redirect(
            url_for(
                "web_experiments.experiment", exp_title=exp.title, username=exp.author
            )
        )

    # pre-populate form
    form.script.data = exp.script
    form.version.data = exp.version

    return render_template(
        "experiment_script.html",
        title="Experiment Script",
        experiment=exp,
        form=form,
        legend="Experiment Script",
    )


@web_experiments.route(
    "/<username>/<path:experiment_title>/delete", methods=["POST", "GET"]
)  # only allow POST request
@login_required
def delete_experiment(username, experiment_title):

    # pylint: disable=no-member
    experiment = WebExperiment.objects.get_or_404(
        title=experiment_title, author=username
    )

    if experiment.author != current_user.username:
        abort(403)
    try:
        shutil.rmtree(experiment.path)
    except FileNotFoundError:
        flash("Experiment directory didn't exist on file system.", "warning")

    experiment.delete()
    flash("Experiment deleted.", "info")

    return redirect(
        url_for("web_experiments.user_experiments", username=current_user.username)
    )


def validate_zipfile_filenames(z: zipfile.ZipFile) -> bool:
    """
    Validates the filenames of files contained in the input zipfile
    object.

    If a filename is a directory or is otherwise not secure, validation
    will fail.

    Returns:
        bool: True, if validation succeeds. False otherwise.
    """
    valid = True
    names = z.namelist()
    sanitized_names = [secure_filename(fname) for fname in names]
    for n1, n2 in zip(names, sanitized_names):
        p1 = Path(n1)
        if not n1 == n2:
            if not p1.suffix:
                flash(
                    f"'{n1}' seems to be a directory, which is not allowed.", "danger"
                )
            else:
                flash(f"Filename '{n1}' is not secure. Please change it.", "danger")
            valid = False
            break
        if p1.suffix not in current_app.config["DROPZONE_ALLOWED_FILE_TYPE"]:
            flash(

src/alfredo/templates/about.html
{% extends "layout.html" %}

{% block content %}
<h1>Welcome to Alfredo</h1>
<div class="content-section">


    <p>Alfredo is a free and open source web application, developed by Christian Treffenstaedt, Paul Wieman and
        Johannes Brachem at the Georg-August-University Goettingen (Germany). </p>


    <p>It's purpose is to host and manage Alfred experiments and surveys (see <a
            href="https://github.com/ctreffe/alfred">Alfred on GitHub</a>).</p>


    <p>If you would like to learn more, you can visit the <a href='https://github.com/ctreffe/alfredo'>Alfredo GitHub
            repository</a>.</p>

</div>

{% endblock content %}

src/alfredo/templates/create_experiment.html
{% extends "layout.html" %}


{% block content %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('web_experiments.new_experiment') }}"
        class="needs-validation" novalidate>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}*
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.version.label(class="form-control-label") }}*
                {% if form.version.errors %}
                {{ form.version(class="form-control form-control-lg is-invalid") }}
                <!-- , placeholder=form.version.label.text -->

                <div class="invalid-feedback">
                    {% for error in form.version.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.version(class="form-control form-control-lg") }}
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>


            <div class="form-group pt-1">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Here, you can protect access to your experiment with a password. Just leave this field empty if you
                    want the experiment to be public.
                </small>
            </div>

            <div class="form-group">
                {{ form.script.label() }}
                {{ form.script(class="form-control-file") }}
                {% if form.script.errors %}
                {% for error in form.script.errors %}
                <span class="text-danger">{{ error }}</span><br>
                {% endfor %}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-primary", id="submit")}}
        </div>
    </form>
</div>

{% endblock content %}

src/alfredo/templates/data.html
{% extends "layout_experiment.html" %}

{% block custom_css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
{% endblock custom_css %}

{% block content %}



<table id="exp-data" class="display">

  <thead>
    <tr>

      {% for col in fieldnames %}
      <th scope="col" class="small">{{ col }}</th>
      {% endfor %}
    </tr>
  </thead>

  <tbody>

    {% for row in data %}
    <tr>
      {% for col in fieldnames %}
        <td class="small text-muted">
        <div data-toggle="tooltip" title="{{ row[col] }}" class="datatab-cell">
          {{ row[col] }}
        </div>
        </td>
      {% endfor %}
    </tr>
    {% endfor %}

  </tbody>
</table>

{% endblock content %}

{% block custom_js %}

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<script>
  $(document).ready(function () {
    $('#exp-data').DataTable({
      "order": [
        [9, "desc"]
      ],
      "scrollX": true,
      "scrollY": "70vh",
      "lengthMenu": [
        [10, 25, 50, 100, 200, -1],
        [10, 25, 50, 100, 200, "All"]
      ],
      "pageLength": 50,
      "columnDefs": [{
        className: "dt-nowrap",
        targets: "_all"
      }],
    });
  });

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  });

  $('.datatab-cell').tooltip(options);
</script>



{% endblock custom_js %}

src/alfredo/templates/exp_preview.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

{# <meta property="og:url"                content="" /> #}
<meta property="og:type"               content="article" />
<meta property="og:title"              content="{{ title }}" />
<meta property="og:description"        content="{{ desc }}" />
<meta property="og:image"              content="{{ url_for('static', filename=logo, _external=True) }}" />
<meta property="og:image"              content="{{ url_for('static', filename=logo_small, _external=True) }}" />

</head>

</html>

src/alfredo/templates/experiment_config.html
{% extends "layout_experiment.html" %}

{% block content %}

<form method="POST" class="needs-validation" action="" novalidate>
    {{ form.hidden_tag() }}

    <h2 class="border-bottom"><i class="fas fa-cog mr-2"></i>Experiment Configuration</h2>

    <div class="form-group">
        <!-- TITLE FORM -->
        <div class="form-group row">
            <div class="col-xl-2 col-form-label">
                {{ form.title.label(class="form-control-label") }}
            </div>
            <div class="col-xl-10">
                {% if form.title.errors %}

                {{ form.title(class="form-control form-control-sm is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.title(class="form-control form-control-sm") }}
                {% endif %}
            </div>
        </div>

        <!-- DESCRIPTION FORM -->
        <div class="form-group row">
            <div class="col-xl-2 col-form-label">
                {{ form.description.label(class="form-control-label") }}
            </div>
            <div class="col-xl-10">
                {% if form.description.errors %}

                {{ form.description(class="form-control form-control-sm is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.description(class="form-control form-control-sm") }}
                {% endif %}
            </div>
        </div>

        <!-- PASSWORD FORM -->
        <div class="form-group row">
            <div class="col-xl-2 col-form-label">
                {{ form.password.label(class="form-control-label") }}
            </div>
            <div class="col-xl-10">
                {% if form.password.errors %}

                {{ form.password(class="form-control form-control-sm is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.password(class="form-control form-control-sm") }}
                {% endif %}
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Here, you can protect access to your experiment with a password. Just leave this field empty if
                    you
                    want the experiment to be public.
                </small>
            </div>
        </div>
    </div>


    <div class="row pt-5">

        <!-- config.conf -->
        <div class="col-xl-6">
            <h3 class="border-bottom">config.conf</h3>

            {% if form.exp_config.errors %}
            {{ form.exp_config(class="form-control form-control-sm is-invalid", style="font-family: 'Dejavu Sans Mono', monospace;" , rows="20") }}

            <div class="invalid-feedback">
                {% for error in form.exp_config.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            {% else %}
            {{ form.exp_config(class="form-control form-control-sm", style="font-family: 'Dejavu Sans Mono', monospace;", rows="20", placeholder="Input config.conf") }}
            {% endif %}

        </div>

        <!-- secrets.conf -->
        <div class="col-xl-6">
            <h3 class="border-bottom">secrets.conf</h3>

            {% if form.exp_secrets.errors %}
            {{ form.exp_secrets(class="form-control form-control-sm is-invalid", style="font-family: 'Dejavu Sans Mono', monospace;" , rows="20") }}

            <div class="invalid-feedback">
                {% for error in form.exp_secrets.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            {% else %}
            {{ form.exp_secrets(class="form-control form-control-sm", style="font-family: 'Dejavu Sans Mono', monospace;", rows="20", placeholder="Input secrets.conf") }}
            {% endif %}

        </div>
    </div>

    {{ form.submit(class="btn btn-primary btn-block mt-3")}}

</form>

{% endblock %}

src/alfredo/templates/experiment_script.html
{% extends "layout_experiment.html" %}

{% block content %}

<div class="content-section">
    <form method="POST" action="" class="needs-validation" novalidate>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom">{{ legend }}</legend>

            <div class="form-group">

                {% if form.script.errors %}
                {{ form.script(class="form-control form-control-sm is-invalid", style="font-family: 'Dejavu Sans Mono', monospace;",  placeholder=experiment.script) }}

                <div class="invalid-feedback">
                    {% for error in form.script.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.script(class="form-control form-control-sm", style="font-family: 'Dejavu Sans Mono', monospace;", rows="30", placeholder=experiment.script) }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.version.label(class="form-control-label") }}*
                {% if form.version.errors %}
                {{ form.version(class="form-control form-control-lg is-invalid") }}
                <!-- , placeholder=form.version.label.text -->

                <div class="invalid-feedback">
                    {% for error in form.version.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.version(class="form-control form-control-lg", placeholder=experiment.version) }}
                {% endif %}
                <small id="versionHelpBlock" class="form-text text-muted">
                    Changing the version number allows you to choose, for which versions of an experiment you want to
                    download data. If you made substantial changes to your experiment, you should change the version.
                </small>
            </div>


        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary")}}
        </div>
    </form>
</div>

{% endblock content %}

src/alfredo/templates/impressum.html
{% extends "layout.html" %}

{% block content %}

<div class='impressum'><h1>Impressum</h1>
 </div>


{% endblock content %}

src/alfredo/templates/layout_experiment.html
{% extends "layout.html" %}

{% block navigation %}

<ul class="nav navbar-nav mr-auto">
    <li class="nav-item">
        <a href="{{ url_for('web_experiments.experiment', exp_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-experiment">
            {% if experiment.active == True %}
            <span class="badge badge-success">active</span>
            {% else %}
            <span class="badge badge-warning">inactive</span>
            {% endif %}<i class="fas fa-home mr-2 ml-2"></i>{{ experiment.title }}</a>
    </li>
    <li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.experiment_script', exp_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-script"><i class="fas fa-code mr-2"></i>Script</a></li>
    <li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.manage_resources', experiment_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-resources"><i class="fas fa-folder mr-2"></i>Resources</a></li>
<li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.data', experiment_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-resources"><i class="fas fa-table"></i> Data</a></li>
    <li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.export', experiment_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-export"><i class="fas fa-download mr-2"></i>Export</a></li>
    <li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.experiment_config', experiment_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-config"><i class="fas fa-sliders-h mr-2"></i>Configuration</a></li>
    <li class="nav-item nav-link">|</li>
    <li class="nav-item"><a
            href="{{ url_for('web_experiments.experiment_log', experiment_title=experiment.title, username=experiment.author) }}"
            class="nav-link active" id="nav-log"><i class="fas fa-clipboard mr-2"></i>Log</a></li>
</ul>

{% endblock %}

src/alfredo/templates/user_experiments.html
{% extends "layout.html" %}

{% block custom_css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
{% endblock custom_css %}

{% block content %}


<table id="exp-overview" class="display">

  <thead>
    <tr>
      <th class="small">Status</th>
      <th class="small">Title</th>
      <th class="small">Last Update</th>
      <th class="small">Created</th>
      <th class="small">Toggle</th>
      <th class="small">Start</th>
      <th class="small">Delete</th>
    </tr>
  </thead>

  <tbody>

    {% for exp in experiments %}
    <tr>

      <td>
        {% if exp.active %}
        <span class="badge badge-success mr-2">active </span>
        {% else %}
        <span class="badge badge-warning mr-2">inactive </span>
        {% endif %}
      </td>

      <th class="strong">
        {% if exp.active %}
        <a href="{{ url_for('web_experiments.experiment', exp_title=exp.title, username=exp.author) }}"
          class="nav-link"> {{ exp.title }}</a>
        {% else %}
        <a href="{{ url_for('web_experiments.experiment', exp_title=exp.title, username=exp.author) }}"
          class="nav-link"> {{ exp.title }}</a>
        {% endif %}
      </th>

      <td class="small text-muted">{{ exp.last_update.strftime('%Y-%m-%d') }}</td>
      <td class="small text-muted">{{ exp.date_created.strftime('%Y-%m-%d') }}</td>

      <td class="small">
        <form method="POST"
          action="{{ url_for('web_experiments.de_activate_experiment', experiment_title=exp.title, username=exp.author) }}">

          {% if exp.active %}
          <button class="btn btn-sm btn-secondary" type="submit"><i
              class='fas fa-stop-circle mr-2'></i>deactivate</button>
          {% else %}
          <button class="btn btn-sm btn-primary" type="submit"><i class='fas fa-play-circle mr-2'></i>activate</button>
          {% endif %}

        </form>
      </td>

      <td class="small">
        {% if exp.active %}
        <a class="btn btn-success btn-sm" target="_blank" rel="noopener noreferrer"
          href="{{ url_for('alfredo.start', expid=exp.id) }}"><i class="fas fa-play mr-2"></i>Start</a>
        {% else %}
        -
        {% endif %}

      </td>

      <td class="small"><button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
          data-target="#deleteModal{{ secure_filename(exp.title) }}"><i class='fas fa-trash mr-2'></i>delete</button>
      </td>

    </tr>

    {% endfor %}



  </tbody>

</table>



{% for exp in experiments %}

<!-- Modal -->
<div class="modal fade" id="deleteModal{{ secure_filename(exp.title) }}" tabindex="-1" role="dialog"
  aria-labelledby="deleteModal{{ secure_filename(exp.title) }}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModal{{ secure_filename(exp.title) }}">Delete Experiment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure that you want to delete this experiment? The data stored in Alfredo will be lost! <br><br>The
        experimental data in the Alfred database will <b>not</b> be deleted by this.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form method="POST"
          action="{{ url_for('web_experiments.delete_experiment', experiment_title=exp.title, username=exp.author) }}">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock content %}

{% block custom_js %}

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<script>
  $(document).ready(function () {
    $('#exp-overview').DataTable({
      "order": [
        [2, "desc"]
      ],
      // "scrollX": true,
      "scrollY": "70vh",
      "lengthMenu": [
        [10, 25, 50, 100, 200, -1],
        [10, 25, 50, 100, 200, "All"]
      ],
      "pageLength": 50,
      "columnDefs": [{
          className: "dt-nowrap",
          targets: "_all"
        },
        {
          "width": "5%",
          "targets": [0]
        }
      ],

    });
  });
</script>

{% endblock custom_js %}