src/mortimer/main/routes.py
import os
import time
from uuid import uuid4

from flask import Blueprint, current_app, redirect, render_template, url_for
from flask_login import current_user, login_required

from mortimer.forms import FuturizeScriptForm
from mortimer.utils import perform_futurization, replace_all_patterns

main = Blueprint("main", __name__)

# this route has two addresses


@main.route("/")
@main.route("/home")
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("users.login"))

    id = str(uuid4())
    return render_template("home.html", id=id)


@main.route("/about")
@login_required
def about():
    return render_template("about.html")


@main.route("/impressum")
def impressum():
    return render_template("impressum.html")


@main.route("/futurize_script", methods=["POST", "GET"])
@login_required
def futurize_script(script_name=None):
    # clean up operation: delete files from the temp directory, if they are older than 15 minutes
    temp_path = os.path.join(current_app.instance_path, "tmp", "futurize_scripts")
    if not os.path.isdir(temp_path):
        os.makedirs(temp_path)
    s_since_epoch = time.time()

    for file in os.listdir(temp_path):
        file_path = os.path.join(temp_path, file)
        creation_of_file = os.path.getmtime(file_path)

        if (s_since_epoch - creation_of_file) > 900:
            os.remove(file_path)

    form = FuturizeScriptForm()

    if form.validate_on_submit():
        filename = str(uuid4()) + ".py"
        filepath = os.path.join(temp_path, filename)
        filepath_bak = os.path.join(temp_path, filename + ".bak")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(form.script.data)

        perform_futurization(filepath)
        replace_all_patterns(filepath)

        with open(filepath, encoding="utf-8") as f:
            new_script = f.read()

        os.remove(filepath)
        try:
            os.remove(filepath_bak)
        except FileNotFoundError:
            pass

        return render_template("futurize_script.html", form=form, new_script=new_script)

    return render_template("futurize_script.html", form=form, script_name=script_name)

src/mortimer/users/routes.py
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user

from mortimer import bcrypt
from mortimer.forms import (
    LoginForm,
    RegistrationForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from mortimer.models import User, WebExperiment
from mortimer.utils import send_register_email, send_reset_email

# pylint: disable=no-member
users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RegistrationForm()

    if form.validate_on_submit():
        if User.objects(username=form.username.data):
            flash("Username already taken. Please choose a different one.", "error")
            return redirect(url_for("users.register"))
        elif User.objects(email=form.email.data):
            flash("Email already taken. Please choose a different one.", "error")
            return redirect(url_for("users.register"))

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        user.encryption_key = User.generate_encryption_key()
        user.set_db_config()

        # save user
        user.save()
        flash("Account created for %s." % form.username.data, "success")

        send_register_email(user)

        return redirect(url_for("users.login"))

    password_hint = "This is a password hint"

    # the named arguments here will be passed to the .html file
    # this way, they can be accessed in jinja2 templates
    return render_template(
        "register.html", title="Register", form=form, password_hint=password_hint
    )


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()  # pylint: disable=no-member

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash("Login Successful.", "success")

            # for backwards compatibility, generate encryption key if there isnt already one
            if not user.encryption_key:
                user.encryption_key = User.generate_encryption_key()
                user.save()

            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check username and password", "danger")

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash("Succesfully logged out", "info")

    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required  # this route can only be accessed by logged in users
def account():
    # pylint: disable=no-member
    form = UpdateAccountForm()

    if form.validate_on_submit():  # if all field are filled out correctly
        if current_user.username != form.username.data:
            for exp in WebExperiment.objects(author=current_user.username):
                exp.author = form.username.data
                exp.save()

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.save()  # save updates to database
        flash("Your account has been updated.", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template(
        "account.html", title="Account", form=form, user=current_user
    )


@users.route("/request_password_reset", methods=["GET", "POST"])
def request_password_reset():
    if current_user.is_authenticated:
        flash("You are currently logged in.", "info")
        return redirect(url_for("main.home"))

    if not current_app.config["MAIL_USE"]:
        flash(
            "Automatic password reset is disabled. Please contact the administrator.",
            "warning",
        )
        return redirect(url_for("main.home"))

    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()  # pylint: disable=no-member
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password", "info")
        return redirect(url_for("users.login"))

    return render_template(
        "request_password_reset.html", title="Reset Password", form=form
    )


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        flash("You are currently logged in.", "info")
        return redirect(url_for("main.home"))

    user = User.verify_reset_token(token)

    if user is None:
        flash("The reset token is either invalid or expired", "warning")
        return redirect(url_for("users.request_password_reset"))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        user.save()
        flash("Your password has been updated.", "success")
        return redirect(url_for("users.login"))

    return render_template("reset_password.html", title="Reset Password", form=form)

src/mortimer/templates/create_experiment.html
{% extends "layout.html" %}


{% block content %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data" action="{{ url_for('web_experiments.new_experiment') }}"
        class="needs-validation" novalidate>
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}*
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.version.label(class="form-control-label") }}*
                {% if form.version.errors %}
                {{ form.version(class="form-control form-control-lg is-invalid") }}
                <!-- , placeholder=form.version.label.text -->

                <div class="invalid-feedback">
                    {% for error in form.version.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.version(class="form-control form-control-lg") }}
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>


            <div class="form-group pt-1">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}

                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>

                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Here, you can protect access to your experiment with a password. Just leave this field empty if you
                    want the experiment to be public.
                </small>
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-primary", id="submit")}}
        </div>
    </form>
</div>

{% endblock content %}

src/mortimer/templates/layout.html
{% extends "skeleton.html" %}

{% block layout %}
<div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar" class="bg-dark">
        <div class="">
            <ul class="list-unstyled comments">
                <li><a href="{{ url_for('main.home') }}" class="pl-3 pt-2">
                        <h3 style="display: inline;">mortimer</h3><small class="text-light"> v{{ mortimer }}</small>
                    </a></li>
            </ul>

        </div>

        <ul class="list-unstyled comments">


            <li><a href="{{ url_for('web_experiments.user_experiments', username=current_user.username) }}"><i
                        class="fas fa-desktop mr-2"></i>Experiments</a></li>
            <li><a href="{{ url_for('web_experiments.new_experiment') }}"><i class="fas fa-plus-circle mr-2"></i>New
                    Experiment</a></li>
            <hr class="lightrule">
            <!-- <li><a href="#"><i class="fas fa-cog mr-2"></i>Settings*</a></li> -->
            <!-- <li><a href="#"><i class="fas fa-question mr-2"></i>Help*</a></li> -->
            <li><a href="{{ url_for('users.account') }}"><i class="fas fa-user mr-2"></i>Account</a></li>
            <hr class="lightrule">
            <!-- <li><a href="#"><i class="fas fa-quote-left mr-2"></i>About*</a></li> -->
            <li><a href="{{ url_for('main.impressum') }}"><i class="fas fa-align-left mr-2"></i>Impressum</a></li>
        </ul>

        <footer style="position: fixed; bottom:0; height:80px;" class="pl-2">
            <a href=" https://github.com/ctreffe/mortimer">
                <small class="text-light"><i class="fab fa-github"></i> mortimer v{{ mortimer }}</small></a><br>
            <a href="https://github.com/ctreffe/alfred">
                <small class="text-light"><i class="fab fa-github"></i> alfred3 v{{ alfred }}</small></a><br>
            <a href="https://github.com/jobrachem/alfred3-interact">
                <small class="text-light"><i class="fab fa-github"></i> alfred3_interact v{{ alfred3_interact }}</small></a>
        </footer>

    </nav>

    <!-- Content -->
    <div id="content">


        <nav class="navbar navbar-light navbar-expand-sm shadow-sm bg-light text-secondary" id="contentNav">
            <div class="container-fluid">

                {% block navigation %}{% endblock %}

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item"><a href="{{ url_for('users.logout') }}" class="nav-link"><i
                                class="fas fa-sign-out-alt mr-2"></i>Logout</a></li>
                </ul>

            </div>
        </nav>

        <div id="contentBody">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    &times;
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block subheading %}{% endblock %}
            {% block content %}{% endblock %}

        </div>



    </div>

</div>

{% endblock %}

src/mortimer/templates/skeleton.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>mortimer</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous"> -->

    <!-- Our Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')}}">

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    {% block custom_css %}{% endblock %}

    <!-- Font Awesome JS -->
    <script src="https://kit.fontawesome.com/3922491632.js" crossorigin="anonymous"></script>
</head>

<body>

    {% block layout %}{% endblock %}

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Custom JS -->

    {% block custom_js %}{% endblock %}

</body>

</html>